### ISSUE TITLE
Shows queue for wrong region on Dashboard

### ISSUE THREAD

**Issue by rawbeans** [njeirath/brenda-web#79]
This bug has mad the site unusable on my AWS account.

I first set everything up on us-west-1, however I decided to move to working on us-east-1 (because there are prebuilt AMIs for this region).

Now when I add tasks to my queue on us-east-1, the dashboard still displays only the us-west-1 queue. It seems like there is some underlying code overriding my us-east-1 setting in the AWS config. - Basically the dashboard gets stuck on whatever the first region you used with the site.

**Comment by njeirath** [comment]
@rawbeans can you confirm if you're still seeing the issue, I just tried and everything seems to be working alright for me.  If you are still seeing an issue, can you confirm if the issue persists even if you refresh the site after changing regions?  Also, any information on what browser & version you're using would be helpful.
