### ISSUE TITLE
Region setting is not transferred to the nodes

### ISSUE THREAD

**Issue by mtoivo** [njeirath/brenda-web#84]
The default startup script (that cannot be modified) does not send SQS_REGION, S3_REGION or EC2_REGION config vars to the nodes. So, if you're trying to use other regions than US, nodes just startup and shutdown right away, because they only try to poll default region, the US.

**Comment by njeirath** [comment]
@mtoivo Merged in what should be a fix for the issue.  Will close this out but let me know if you have any other issues.
